/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class example_jni_print_PrintLine */

#ifndef _Included_example_jni_print_PrintLine
#define _Included_example_jni_print_PrintLine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     example_jni_print_PrintLine
 * Method:    printLine
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_example_jni_print_PrintLine_printLine
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
